### ISSUE TITLE
Get rid of settings.py

### ISSUE THREAD

**Issue by tundish** [ONSdigital/sdx-rabbit-monitor#2]
If we want this to be a single-file program, we should get rid of having to import settings.py

One way to do this would be to define configuration variables as argparse options instead, and give them the default values which appear now in settings.py

A convenient way to configure for different environments is populating the CLI options from a text file:
https://docs.python.org/3/library/argparse.html#fromfile-prefix-chars

**Comment by JamesGardiner** [comment]
I'm closing this as this approach maintains consistency with other SDX services.
